### ISSUE TITLE
[Not an issue] Best way to contact you?

### ISSUE THREAD

**Issue by Sweenus** [Konsyliarz42/simplyswords-vanilla-style#2]
Hey there,

Simply Swords dev here 👋
Sorry for popping this into your issue tracker, but I can't find another way to contact you.
I was hoping to discuss some stuff with you, if you're willing - do you have a discord or another method of contact you can provide me with?

Cheers,

**Comment by Konsyliarz42** [comment]
Hi, you can contact with me by this mail: dotomika@gmail.com
